ALTER TABLE dim_store_details
ALTER COLUMN longitude SET DATA TYPE FLOAT USING longitude::float,
ALTER COLUMN locality SET DATA TYPE VARCHAR(255),
ALTER COLUMN store_code SET DATA TYPE VARCHAR(50),
ALTER COLUMN staff_numbers SET DATA TYPE SMALLINT USING staff_numbers::smallint,
ALTER COLUMN opening_date SET DATA TYPE DATE USING opening_date::date,
ALTER COLUMN store_type DROP NOT NULL,
ALTER COLUMN store_type SET DATA TYPE VARCHAR(255), 
ALTER COLUMN latitude SET DATA TYPE FLOAT USING latitude::float,
ALTER COLUMN country_code SET DATA TYPE VARCHAR(5),
ALTER COLUMN continent SET DATA TYPE VARCHAR(255)